### ISSUE TITLE
not working on vim for windows

### ISSUE THREAD

**Issue by sangshuduo** [uguu-org/vim-matrix-screensaver#8]
am I alone?

**Comment by KnoP-01** [comment]
Running fine here. Vim and GVim.

Windows 10 21H1 19043.1110
VIM - Vi IMproved 8.2 Included patches: 1-2738

Try with (gvim or) vim -N -u NONE -U NONE

If that works it is your configuration.

**Comment by sangshuduo** [comment]
works now. I probably missed something in vimrc.
